kind: Deployment
apiVersion: apps/v1
metadata:
  name: tomcat-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
       - name: tomcat
         image: mithi5/my-app:latest
         ports:
          - containerPort: 8080





---


kind: Service
apiVersion: v1
metadata:
  name: tomcat-service
spec:
  type: NodePort
  selector:
     app: tomcat
  ports:
   - name: http
     protocol: "TCP"
     port: 8080
     targetPort: 80
